name: GSA
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fiona>=1.8.18
  - gdal>=3.1.4
  - geopandas>=0.11.1
  - libcurl>=7.76.1
  - matplotlib>=3.2.2
  - pandas>=1.4.3
  - pip>=22.2.2
  - rasterio>=1.2.1
  - scipy>=1.9.0
  - seaborn>=0.11.2
  - snakemake-minimal>=5.19.2
  - pytest
  - pip:
    - numpy>=1.21.6
    - sklearn>=0.0
    - salib>=1.4
    - rasterstats>= 0.8
